language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  - chmod u+x gradlew
  - ./gradlew clean
  - ./gradlew build
